image:
  file: .gitpod.dockerfile
ports:
- port: 8080
  onOpen: open-preview
tasks:
- name: Terminal
  command: >
    echo "";
    echo "Commands you can try:";
    echo " * apachectl stop";
    echo " * apachectl start";
    echo " * gp open /var/log/apache2/access.log";
    echo " * gp open /var/log/apache2/error.log";
- name: Apache
  command: >
    git clone https://github.com/gitpod-io/apache-example.git;
    sudo cp apache-example/apache/apache.conf /etc/apache2/apache2.conf;
    rm -rf apache-example/;
    git clone https://github.com/jgodstime/team-fury-1.git;
    mv team-fury-1/ www;
    apachectl start &&
    multitail /var/log/apache2/access.log -I /var/log/apache2/error.log
