image:
  file: .gitpod.dockerfile
ports:
- port: 8080
  onOpen: open-preview
tasks:
- name: Terminal
  command: >
    git clone https://github.com/jgodstime/team-fury-1.git;
    mv team-fury-1/* www/
    echo "";
    echo "Commands you can try:";
    echo " * apachectl stop";
    echo " * apachectl start";
    echo " * gp open /var/log/apache2/access.log";
    echo " * gp open /var/log/apache2/error.log";
- name: Apache
  command: >
    apachectl start &&
    multitail /var/log/apache2/access.log -I /var/log/apache2/error.log
